name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name : List Directory
      run: | 
       pwd
       ls -la
       
    - uses: actions/checkout@v4

    - name : List AFTER
      run:  ls -la
        

    - name: Run a multi-line script
      run: echo "Hello , world!" >> 1.txt
      
    - name: Run a multi-line script
      run: |
          echo "Hello , world 22222!" >> 1.txt
          echo "Hello , world 33333!" >> 1.txt
          cat 1.txt
          
